### ISSUE TITLE
Build android apk失败

### ISSUE THREAD

**Issue by karma-sun** [BFWXKJGS/AlistClient#1]
Build android apk失败,似乎缺失文件

FAILURE: Build failed with an exception.

* Where:
Build file '/root/AlistClient/android/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not read script '/root/AlistClient/android/privacy.gradle' as it does not exist.

**Comment by GeekTR** [comment]
这个是密钥相关的配置文件，我们没有上传。如果你需要编译可以尝试修改在app目录下修改build.gradle文件。

1. 删除 signingConfigs 的配置；
2. buildTypes.debug 修改为 signingConfig signingConfigs.debug
3. 删除 buildTypes.release相关配置
