### ISSUE TITLE
希望添加以下功能

### ISSUE THREAD

**Issue by ypq123456789** [BFWXKJGS/AlistClient#10]
1.缩略图功能。（已完成）
2.视频播放功能的完善，例如可以直接点击进度条，长按倍速播放等。
3.文件管理功能，包括移动、复制、删除、上传，以及下载等。（已完成）下载管理缺少直接删除任务和文件功能
4.账户切换功能，无需退出登录就可以切换账户。（已完成）

辛苦各位大佬了！你们干的事情很伟大！你们慢慢来，知道需求就好啦，我可以慢慢等你们完善！加油！谢谢你们无私的奉献

**Comment by GeekTR** [comment]
你说的大部分功能已经在开发中了

**Comment by ypq123456789** [comment]
> 你说的大部分功能已经在开发中了

谢谢大佬，感谢！辛苦啦
