### ISSUE TITLE
登录不上去，一直在加载，重装后解决

### ISSUE THREAD

**Issue by ypq123456789** [BFWXKJGS/AlistClient#13]
提示token过期，然后尝试登录，不管是内网还是外网，一直都是loading加载中。

![微信图片_20230627190031](https://github.com/BFWXKJGS/AlistClient/assets/114487221/fe0b8f32-45a5-4b03-8a3b-8b323da76c67)

卸载重新安装后，问题得到解决了，但还是不知道出现这个问题的原因是啥。

**Comment by GeekTR** [comment]
有更新吗？

**Comment by GeekTR** [comment]
是不是更新之后，然后token失效了，然后就登不上去

**Comment by GeekTR** [comment]
已修复
