### ISSUE TITLE
挂在本地磁盘和FTP服务器，任何音乐都不播放，只显示打开音乐，没有声音，没有进度，也没有时常

### ISSUE THREAD

**Issue by xiureal** [BFWXKJGS/AlistClient#16]
挂载本地磁盘和FTP服务器，任何音乐都不播放，只显示打开音乐，没有声音，没有进度，也没有时常
![Screenshot_20230720_093554_com github alist clien](https://github.com/BFWXKJGS/AlistClient/assets/108256125/926409b6-3e46-4ce6-a8df-c64b802fa3ab)

**Comment by GeekTR** [comment]
挂载的ftp？我还没试过，我待会儿看看。你这个是什么版本

**Comment by xiureal** [comment]
> 挂载的ftp？ 我还没试过，我待会儿看看。 你这个是什么版本

大佬 那个1.03的app还是能正常播放MP3的，但是 1.04的就不行，1.04的APP是所有的音乐格式都不能正常那播放，用的alist是最新版3.22.1的，挂载本地的 磁盘也是不能播放的，我用的是tp路由器挂载的U盘提供的FTP

**Comment by GeekTR** [comment]
试试新版本

**Comment by xiureal** [comment]
> 试试新版本
感谢大佬，十分感谢，还有就是能不能增加更多的音乐格式，比如ape等无损格式的音乐。酷狗QQ音乐等无损格式

**Comment by GeekTR** [comment]
酷狗QQ音乐他们的都是自带加密的，难度太大做不了
