### ISSUE TITLE
文件上传异常、最近缩略图不显示

### ISSUE THREAD

**Issue by ypq123456789** [BFWXKJGS/AlistClient#17]
![48f908d824b3af2d36297b3b48d23b7](https://github.com/BFWXKJGS/AlistClient/assets/114487221/339ce99c-6917-45ce-b7b3-70d087606a4d)
上传文件一直显示网络异常，不知道为啥

![98f4dd3190bd38a39154d36be618633](https://github.com/BFWXKJGS/AlistClient/assets/114487221/eb5d5ae0-fdab-41dd-98bf-7e3decae2f3e)
最近的缩略图一直不显示

辛苦大佬查找问题啦

**Comment by GeekTR** [comment]
上传异常那个已经改过了，缩略图的我再看看。你这个哪个版本

**Comment by ypq123456789** [comment]
> 上传异常那个已经改过了，缩略图的我再看看。你这个哪个版本

就是最新版本，大佬，1.0.4

**Comment by GeekTR** [comment]
github 漏了个版本，上传异常那个我们好像1.0.5改过了，你试试google play下个1.0.5看看

**Comment by ypq123456789** [comment]
> 

不好意思大佬，我手机华为的很难装google play，github这边啥时候更新呀，我到时候下载好啦

**Comment by GeekTR** [comment]
好的，我们这边改几个bug尽快提交一下

**Comment by GeekTR** [comment]
试试新版本

**Comment by ypq123456789** [comment]
没问题了大佬，都可以了
