### ISSUE TITLE
建议支持搜索功能

### ISSUE THREAD

**Issue by houlijiang** [BFWXKJGS/AlistClient#21]
建议支持搜索功能，文件夹，文件名称的搜索功能，什么时候可以支持？

**Comment by ElaineTaylor** [comment]
目前我们在开发一个比较重要的功能，您提的意见我们这边会做好统计，再次感谢提供宝贵的意见～

**Comment by GeekTR** [comment]
搜索功能已支持，需在后台开启搜索并构建索引
