### ISSUE TITLE
AList 安卓客户端功能实现

### ISSUE THREAD

**Issue by wzry2580** [BFWXKJGS/AlistClient#3]

**Comment by wzry623090** [comment]
> 我希望可以实现上传文件者新建文件夹功能，调用手机管理器之类的上传文件，我是问一下，是否能实现？ AList 网页端有的功能，希望安卓端也能实现功能肯定不可能那么完善，尽量实现基础的上传以及新建文件夹之类的功能

**Comment by GeekTR** [comment]
这个功能肯定会做的，可以实现。但是我们人手不够，做起来需要时间

**Comment by wzry623090** [comment]
> 这个功能肯定会做的，可以实现。但是我们人手不够，做起来需要时间

 没事，我能等，

**Comment by GeekTR** [comment]
上传文件以及新建文件夹功能已完成。
