### ISSUE TITLE
怎样才能实现连播呢？

### ISSUE THREAD

**Issue by ZhuMing19920416** [BFWXKJGS/AlistClient#46]
用第三方播放器比如mxplayer，播放电视剧等需要连续播放的怎样才能实现自动连播呢，并且留下历史记录。

**Comment by GeekTR** [comment]
用三方播放器实现不了连播

**Comment by ZhuMing19920416** [comment]
有可能在未来版本实现吗？个人感觉看视频的话挺需要的，自带的播放器性能还差点意思。



---原始邮件---
发件人: "Rui ***@***.***&gt;
发送时间: 2024年7月26日(周五) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BFWXKJGS/AlistClient] 怎样才能实现连播呢？ (Issue #46)




 
用三方播放器实现不了连播

**Comment by GeekTR** [comment]
你用过哪个app使用三分播放器还可以连播的吗？
