### ISSUE TITLE
可否增加自定义端口登录

### ISSUE THREAD

**Issue by maple185** [BFWXKJGS/AlistClient#5]
在“服务器地址”使用直接添加端口（http://qq.com:666/dav）的方式，返回“数据解析异常”，可否增加自定义端口登录选项方便非默认端口的外网访问。

希望可以增加自动同步功能，方便把手机相册同步回远程家庭电脑存储备份。

**Comment by anwen-anyi** [comment]
不需要添加 /dav ~
而且端口是在 AList config.json文件配置的吧 这个软件只是一个客户端

**Comment by maple185** [comment]
> 不需要添加 /dav ~ 而且端口是在 AList config.json文件配置的吧 这个软件只是一个客户端

看来应该是我电脑的问题，我换了一台电脑就可以了

**Comment by GeekTR** [comment]
文件备份可能要晚一点才做了。
