### ISSUE TITLE
建议增加播放列表

### ISSUE THREAD

**Issue by dmc420** [BFWXKJGS/AlistClient#6]
最近用这个听有声书，每个目录是一本书，由多个编好序的音频文档组成，目前播放很顺畅，但是播完了一段需要退出重新打开另一段，希望能增加播放列表，支持自动切换下一集。

辛苦评估大佬下需求。

**Comment by dmc420** [comment]
另外希望增加更多的音频格式，目前mp3表现良好，flac无法播放

**Comment by GeekTR** [comment]
播放列表在计划之内，flac这个需要找到一个合适的方案在做

**Comment by GeekTR** [comment]
已支持
