### ISSUE TITLE
是否支持下载功能

### ISSUE THREAD

**Issue by zhang-001** [BFWXKJGS/AlistClient#7]
是否支持下载功能

**Comment by GeekTR** [comment]
暂时支持下载到沙盒，下载保存到相册或外部文件暂未支持

**Comment by zhang-001** [comment]
> 暂时支持下载到沙盒，下载保存到相册或外部文件暂未支持

后续支持不 大佬

**Comment by GeekTR** [comment]
后续会支持的

**Comment by zhang-001** [comment]
> 后续会支持的

下载功能有个大概的预计时间吗

**Comment by GeekTR** [comment]
由于我们是业余时间开发，所以时间不会很确定，你这个需求大概会在2个月左右实现
